In [1]:
from quarto import objects, players, extensions
import logging
import math
from copy import deepcopy
from tqdm.notebook import tqdm

In [2]:
import numpy as np

g = objects.Quarto(np.array([[2,12,7,-1],[4,14,5,3],[8,0,9,6],[13,-1,-1,1]]))
print(g.check_winner())
print(g._Quarto__board)
g.select(11)
mm = players.MinMaxPlayer(g, max_combs=math.factorial(2) ** 2)
x, y = mm.place_piece()
g.place(x, y)

-1
[[ 2 12  7 -1]
 [ 4 14  5  3]
 [ 8  0  9  6]
 [13 -1 -1  1]]
[10, 15] at depth 0
[(3, 0), (1, 3), (2, 3)] at depth 0
Placing 11 at (0, 3) at depth 0
Placing 10 at (3, 1) at depth 1
Winner: 1 at depth 1
Placing 10 at (3, 2) at depth 1
Placing 15 at (3, 1) at depth 2
Move (0.5, ((3, 2), 15)) at depth 1
Move (1, ((0, 3), 10)) at depth 0
Placing 15 at (3, 1) at depth 1
Placing 10 at (3, 2) at depth 2
Winner: 0.5 at depth 2
Move (0.5, ((3, 1), 10)) at depth 1
Placing 15 at (3, 2) at depth 1
Winner: 1 at depth 1
Move (1, ((0, 3), 15)) at depth 0
Placing 11 at (3, 1) at depth 0
Placing 10 at (0, 3) at depth 1
Placing 15 at (3, 2) at depth 2
Winner: 0 at depth 2
Move (0, ((0, 3), 15)) at depth 1
Placing 10 at (3, 2) at depth 1
Placing 15 at (0, 3) at depth 2
Winner: 0.5 at depth 2
Move (0.5, ((3, 2), 15)) at depth 1
Move (0.5, ((3, 1), 10)) at depth 0
Placing 15 at (0, 3) at depth 1
Placing 10 at (3, 2) at depth 2
Winner: 0.5 at depth 2
Move (0.5, ((0, 3), 10)) at depth 1
Placing 15 at (3, 

True

In [3]:
GAMES = 1000

scores = {
    'me': 0,
    'opponent': 0,
    'draw': 0
}

home = {
    0: 'me',
    1: 'opponent',
    -1: 'draw'
}

away = {
    0: 'opponent',
    1: 'me',
    -1: 'draw'
}

MAX_DEPTH = 1
MAX_COMBS = math.factorial(6) ** 2

for _ in tqdm(range(GAMES // 2), desc='Home games'):
    game = objects.Quarto()
    game.set_players((players.MinMaxPlayer(game, max_depth=MAX_DEPTH, max_combs=MAX_COMBS), players.RandomPlayer(game)))
    winner = home[game.run()]
    scores[winner] += 1

logging.warning(f"Stats: {scores}") 

for _ in tqdm(range(GAMES // 2), desc='Away games'):
    game = objects.Quarto()
    game.set_players((players.RandomPlayer(game), players.MinMaxPlayer(game, max_depth=MAX_DEPTH, max_combs=MAX_COMBS)))
    winner = away[game.run()]
    scores[winner] += 1

logging.warning(f"Stats: {scores}")

Home games:   0%|          | 0/500 [00:00<?, ?it/s]

Away games:   0%|          | 0/500 [00:00<?, ?it/s]

In [2]:
from math import factorial


print([(i+1, '{:e}'.format(factorial(i+1) ** 2)) for i in range(16)])

[(1, '1.000000e+00'), (2, '4.000000e+00'), (3, '3.600000e+01'), (4, '5.760000e+02'), (5, '1.440000e+04'), (6, '5.184000e+05'), (7, '2.540160e+07'), (8, '1.625702e+09'), (9, '1.316819e+11'), (10, '1.316819e+13'), (11, '1.593351e+15'), (12, '2.294425e+17'), (13, '3.877579e+19'), (14, '7.600054e+21'), (15, '1.710012e+24'), (16, '4.377631e+26')]


In [8]:
'[[ 2 12  7 -1] [ 4 14  5  3] [ 8  0  9  6] [13 11 -1  1]]'.replace('[  ', '[').replace('[ ', '[').replace('  ', ',').replace(' ', ',')

'[[2,12,7,-1],[4,14,5,3],[8,0,9,6],[13,11,-1,1]]'

In [3]:

home = {
    0: 'me',
    1: 'opponent',
    -1: 'draw'
}

away = {
    0: 'opponent',
    1: 'me',
    -1: 'draw'
}

game = objects.Quarto()
game.set_players((players.MinMaxPlayer(game, 1, max_combs=math.factorial(6)**2), players.RandomPlayer(game)))
winner = game.run()
print(f'Winner is {winner} ({home[winner]})')
print(f'Played {sum(sum(game.get_board_status() != -1))} turns')

Choosing... Best move: (0.5, ((0, 0), 0))
0 selected 0
1 placed 0 at (1, 2)
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1  0 -1 -1]
 [-1 -1 -1 -1]]
1 selected 2
Placing... Best move: (0.5, ((0, 0), 1))
0 placed 2 at (0, 0)
[[ 2 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1  0 -1 -1]
 [-1 -1 -1 -1]]
Choosing... Best move: (0.5, ((0, 0), 1))
0 selected 1
1 placed 1 at (3, 3)
[[ 2 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1  0 -1 -1]
 [-1 -1 -1  1]]
1 selected 4
Placing... Best move: (0.5, ((0, 1), 3))
0 placed 4 at (0, 1)
[[ 2 -1 -1 -1]
 [ 4 -1 -1 -1]
 [-1  0 -1 -1]
 [-1 -1 -1  1]]
Choosing... Best move: (0.5, ((0, 1), 3))
0 selected 3
1 placed 3 at (3, 1)
[[ 2 -1 -1 -1]
 [ 4 -1 -1  3]
 [-1  0 -1 -1]
 [-1 -1 -1  1]]
1 selected 8
Placing... Best move: (0.5, ((0, 2), 5))
0 placed 8 at (0, 2)
[[ 2 -1 -1 -1]
 [ 4 -1 -1  3]
 [ 8  0 -1 -1]
 [-1 -1 -1  1]]
Choosing... Best move: (0.5, ((0, 2), 5))
0 selected 5
1 placed 5 at (2, 1)
[[ 2 -1 -1 -1]
 [ 4 -1  5  3]
 [ 8  0 -1 -1]
 [-1 -1 -1  1]]
1 selected 12
Placing... Best move: (0.5, ((